---
title: "STA 9715 - Notes"
---

Supplemental course notes will be posted here.

#### Week 1: Foundations of Probability

- Quanta Magazine: "[Perplexing the Web, One Probability Puzzle at a Time](https://www.quantamagazine.org/perplexing-the-web-one-probability-puzzle-at-a-time-20240829/)"
- WIRED Magazine: "[Statistician Answers Stats Questions From Twitter 
| Tech Support](https://www.youtube.com/watch?v=QW3KRaz4aI4)"
  - [More Jeff Rosenthal](https://www.youtube.com/watch?v=GNX7cRhWVi0)
- [Harvard STAT 110 Playlist](https://www.youtube.com/playlist?list=PL2SOU6wwxB0uwwH80KTQ6ht66KWxbzTIo)
  - This is the course on which our textbook (BH) is based

#### Week 2: Conditionality and Marginality

- The YouTube channel `3blue1brown` makes excellent 'explainers' about a variety
  of mathematical topics. Check out his videos on Bayes' rule: 
  - [The Geometry of Changing Beliefs](https://www.youtube.com/watch?v=HZGCoVF3YvM)
    - See also [A Quick Proof of Bayes Theorem](https://www.youtube.com/watch?v=U_85TaXbeIo)
  - [The Medical Test Paradox](https://www.youtube.com/watch?v=lG4VkPoG3ko&)
- [Conditioning: The Soul of Statistics](https://www.youtube.com/watch?v=dzFf3r1yph8)
- [Notes on Expectations](./notes/expectations.html)

#### Week 3: Discrete Probability

- [Notes on Discrete Distributions](./notes/discrete_distributions.html)

#### Week 4: From Discrete to Continuous Random Variables

- [Notes on Continuous Random Variables](./notes/continuous_rvs.html)

#### Week 5: Heavy Tails

- [Notes on Tails of Distributions and Implications for Statistical Inference](./notes/tails.html)

#### Week 6: Random Vectors

- [Notes on Vectors](./notes/random_vectors.html)
- [Quanta Article on Probability Puzzles](https://www.quantamagazine.org/perplexing-the-web-one-probability-puzzle-at-a-time-20240829/)

#### Week 7: Covariance and Correlation

- [Notes on Covariance](./notes/covariance.html)


#### Week 8: The Multivariate Normal Distribution and its Progeny

- [3Brown1Blue - "Why $pi$ is in the Normal Distribution"](https://www.youtube.com/watch?v=cy8r7WSuT1I)
- [3Brown1Blue - "A Pretty Reason why Gaussian + Gaussian = Gaussian"](https://www.youtube.com/watch?v=d_qvLDhkg00)
- [Multivariate Normal Distribution Notes](./notes/normal.html)

#### Week 9: Probability, Polling, and Prediction

- [How the Washington Post Estimates Outstanding Votes for the 2020 Presidential Election](https://elex-models-prod.s3.amazonaws.com/2020-general/write-up/election_model_writeup.pdf)

#### Week 10: Perils and Paradoxes in Expectations

#### Week 11: Probability Inequalities and Limit Theorems

#### Week 12: Distributional Limits and the Central Limit Theorem

#### Week 13: Concentration of Measure: Generalized Limit Theory

#### Week 14: Computing with Randomness

#### Exam Materials

- Test 1: 
  - [Formula Sheet](./notes/Test1/FormulaSheet.pdf)
  - [Exam Packet](./notes/Test1/ExamPacket.pdf)
  - [Solutions](./notes/Test1/solutions.html)
  
- Test 2: 
  - [Formula Sheet](./notes/Test2/FormulaSheet.pdf)

