---
title: "STA 9715 - Course Learning Objectives"
editor: 
  markdown: 
    wrap: 80
---

## Official Course Description

This course provides a comprehensive introduction to applied probability and
probability distributions. Students will learn probability with an understanding
of its applications in statistical inference. Topics include discrete and
continuous random variables and distributions, such as the binomial, negative
binomial, Poisson, geometric, uniform, normal, exponential, gamma ($\Gamma$),
beta ($B$), chi-square ($\chi^2$), $t$, and $F$ distributions. This course
thoroughly develops topics as transformation of variables, joint distributions,
bivariate normal, expectations, conditional distributions and expectations,
moment-generating functions, distribution of sums of random variables, means and
variances of sums, ratios of independent variables, and central limit theorem.
Students will acquire an excellent background to proceed to statistical
inference.

## Course Learning Objectives

Students successfully completing STA 9715 will:

1.  Define and manipulate probability mass and density, expectation, and
    variance for discrete and continuous random variables.
2.  Define and manipulate *conditional* probability, expectation, and variance.
3.  Define and manipulate important named probability distributions including,
    but not limited to, the normal distribution, uniform distribution, and
    $t$-distribution.
4.  Manipulate collections of random variables, characterizing them in terms of
    covariance and correlation, and establishing properties of their limits and
    sums.
5.  Define and manipulate *concentration of measure* phenomena including the
    central limit theorem.

Additionally, STA 9715 will review important mathematical concepts used
elsewhere in the statistics curriculum.

The following course elements contribute to these goals:

| Practice Problems | Learning Goal 1 | Learning Goal 2 | Learning Goal 3 | Learning Goal 4 | Learning Goal 5 |
|:-------------------:|:----------:|:----------:|:----------:|:----------:|:----------:|
|      Week 1       |      **✓**      |                 |                 |                 |                 |
|      Week 2       |      **✓**      |      **✓**      |                 |                 |                 |
|      Week 3       |      **✓**      |                 |      **✓**      |                 |                 |
|      Week 4       |      **✓**      |                 |      **✓**      |                 |                 |
|      Week 5       |      **✓**      |      **✓**      |      **✓**      |                 |                 |
|      Week 6       |      **✓**      |      **✓**      |      **✓**      |      **✓**      |                 |
|      Week 7       |      **✓**      |      **✓**      |      **✓**      |      **✓**      |                 |
|      Week 8       |      **✓**      |      **✓**      |      **✓**      |      **✓**      |                 |
|      Week 10      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |
|      Week 11      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |
|      Week 12      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |
|      Week 13      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |      **✓**      |

: Contribution of Course Elements to Learning Goals

## Program Learning Goals

This course contributes to the [program learning
goals](https://zicklin.baruch.cuny.edu/faculty-research/faculty-staff/assurance-of-learning/)
of several MS programs offered by the Zicklin School of Business.

### MS in Business Analytics

This course contributes to the following Program Learning Goals for the MS in
Business Analytics:

| STA 9715 Learning Goal |               MSBA Learning Goal               | Description                                                                                                                                                                                                          |
|:----------------:|:----------------:|:-------------------------------------------|
|                        |                Data Management                 | Students will be able to apply methods, tools, and software for acquiring, managing/storing, and accessing structured and unstructured data. Students will also demonstrate knowledge of the strategic uses of data. |
|         **✓**          | Foundational Statistical / Quantitative Skills | Students will be able to prepare data for statistical analysis, perform basic exploratory and descriptive analysis as well as employ foundational statistical techniques needed to analyze data.                     |
|         **✓**          |    Advanced Statistical/Quantitative Skills    | Students will be able to build and interpret advanced predictive models. Students will be able to combine business rules and mathematical models to optimize business decisions from data.                           |
|         **✓**          |               Ethical Awareness                | Students will be able to articulate an understanding of ethical issues in all phases of business analytics with particular emphasis on the new possibilities afforded by the emergence of big data.                  |
|         **✓**          |           Professional Communication           | Students will be able to explain complex analytical models and their results orally and in writing to technical and non technical/lay audiences.                                                                     |
|                        |             Knowledge Integration              | Students will be able to apply the three key types of analytics (descriptive, predictive, and prescriptive) in a business domain to add value to business decision-making.                                           |

: MSBA Program Learning Goals

### MS in Quantitative Methods & Modeling

This course contributes to the following Program Learning Goals for the MS in
Quantitative Methods & Modeling:

| STA 9715 Learning Goal |             MSQMM Learning Goal             | Description                                                                                                                                                                                                 |
|:----------------:|:----------------:|:-------------------------------------------|
|         **✓**          | Operations Research & Mathematical Modeling | Students will be able to effectively model, evaluate, and solve quantitative (business) problems using quantitative modeling methods (e.g. deterministic and probabilistic operations research techniques). |
|         **✓**          |                 Statistics                  | Students will be able to correctly apply appropriate statistical methods when defining, solving, and analyzing problems.                                                                                    |
|                        |            Technology Competency            | Students will be able to use current technological tools, including spreadsheets and specialized software, when solving problems.                                                                           |
|         **✓**          |         Professional Communication          | Students will be able to effectively communicate their problem solving methods and solutions to technical and non-technical audiences.                                                                      |

: MSQMM Program Learning Goals

### MS in Statistics

This course contributes to the following Program Learning Goals for the MS in
Statistics:

| STA 9715 Learning Goal |     MS Stat Learning Goal      | Description                                                                                                                                                                                                                                                                                                                           |
|:----------------:|:----------------:|:-------------------------------------------|
|         **✓**          | General Statistical Competence | Students will be able to apply appropriate probability models and statistical techniques when analyzing problems frm business and other fields.                                                                                                                                                                                       |
|         **✓**          |      Statistical Practice      | Students will become familiar with the standard tools of statistical practice for multiple regression, along with the tools of a subset of specialized statistical areas such as multivariate analysis, applied sampling, time series analysis, experimental design, data mining, categorical analysis, and/or stochastic processes.  |
|                        |     Technology Competency      | Students will learn to use one or more of the benchmark statistical software platforms, such as SAS or R.                                                                                                                                                                                                                             |

: MS Statistics Program Learning Goals
