---
title: "STA 9715 - Course Syllabus"
---

## Instructor

-   [Professor Michael Weylandt](https://michael-weylandt.com)
-   Department of Information Systems & Statistics
-   Zicklin School of Business
-   Baruch College, CUNY

## Course Meetings

#### Lectures

-   Mondays 6:05pm-9:00pm (In-Person)
    -   [Baruch Main Campus (1 Bernard Baruch Way)](https://www.baruch.cuny.edu/campus-map-and-directions/)
    -   Newman Vertical Campus (NVC) 9-170

#### Office Hours

-   In-Person
    -   [Baruch Main Campus (1 Bernard Baruch Way)](https://www.baruch.cuny.edu/campus-map-and-directions/)
    -   Newman Vertical Campus (NVC) 11-246
    -   Mondays 4:30-5:30pm
    -   Subject to periodic cancellation (communicated via Brightspace)
-   Virtual:
    -   Thursdays 4:30pm-5:30pm
    -   Zoom link provided via Brightspace

## Grading

-   50% Mid-Semester Tests (Best two of three; 100 points each; 200 points total)
    -   October 7th, covering Weeks 1-4
    -   November 11th, covering Weeks 5-8
    -   December 9th, covering Weeks 10-13
-   50% Comprehensive Final Exam (200 points total)
    -   Scheduled by Baruch Registrar ([*tentatively* December 16th at 6:00pm](https://enrollmentmanagement.baruch.cuny.edu/registrar/final-exams/))

Small amounts of *extra credit* will be given for active and helpful participation in the course discussion board (Piazza) at the instructor's discretion.

**Final course grades will be curved in accordance with relevant program, departmental, school, and college policies.**[^1]

[^1]: Theoretically, this may result in scores equivalent to an `A` in an un-curved course receiving a lower grade in this course. In practice, the instructor will design course assessments to induce a range of scores and does not anticipate "down-curving" happening.

#### Weekly Quizzes

In lieu of homework, I will provide a short list of *practice problems* following each lecture. At the start of the following lecture, a short (15 minute) quiz *drawn closely from the practice problems* will be administered. The quiz questions will not be **verbatim** from the practice problems, but if you can answer the practice problems quickly and fluently, the quiz should pose little difficulty.

These in-class weekly quizzes will generate *extra credit* applied to your *final aggregate score*. Each quiz will receive a score out of 3 added directly to your final score. Because the final aggregate score is out of 400, perfect scores on all 12 weekly quizzes can raise your final aggregate score (*pre-curve*) **up to 9%**.

To take part in the weekly quizzes, please come to class with both
i) a black or blue pen; and ii) a red pen (for peer grading) each
week. 

Make-up opportunities for the weekly quizzes will only be allowed in *exceptional* and *unforeseeable* circumstances.

#### Regrading Policy

If you feel an assignment has been improperly graded, please contact the instructor by private message on the course discussion board within 48 hours of the graded assignment being returned. Note that the instructor will regrade the assignment *de novo*, so your grade may be adjusted upwards or downwards.

## Tentative Course Schedule

+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| Week    | Lecture Date                                      | Topics                                                                           | Pre-Reading                       | Post-Reading                     | Practice Problems                                                         | Mid-Semester Tests                 |
+:=======:+==================================================:+:=================================================================================+:=================================:+:================================:+===========================================================================+===================================:+
| 1       | September 9th, 2024                               | Foundations of Probability:                                                      | DFO §6.1,                         | BH §1.1-1.4, §1.6-1.7, §A.1-A.2  | BH §1.9: 3, 4, 5, 12, 15, 23, 24, 26, 28, 29, 31, 41, 44, 45, 49          |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Course Overview                                                              | GS §1.2, §3.1-3.3                 |                                  |                                                                           |                                    |
|         |                                                   | 2.  The Logic of Theory                                                          |                                   |                                  |                                                                           |                                    |
|         |                                                   | 3.  Probability Axioms                                                           |                                   |                                  |                                                                           |                                    |
|         |                                                   | 4.  Elements of Combinatorics                                                    |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 2       | September 16th, 2024                              | Conditionality and Marginality:                                                  | DFO §6.3                          | BH §2.1-2.9, §4.1-4.6, §A.8-A.10 | BH §2.11: 1, 3, 9, 11, 14, 19, 30, 48, 59                                 |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Conditional Probabilities                                                    | GS §4.1, 6.1-6.2                  |                                  | §4.12: 2, 6, 12, 14, 34, 55,                                              |                                    |
|         |                                                   | 2.  Expectation                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 3.  Variance                                                                     |                                   |                                  |                                                                           |                                    |
|         |                                                   | 4.  Moments                                                                      |                                   |                                  |                                                                           |                                    |
|         |                                                   | 5.  Conditional Expectation                                                      |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 3       | September 23rd, 2024                              | Discrete Probability Calculations:                                               | GS §5.1                           | BH §3.1-3.10                     | BH: §3.12: 2, 3, 6, 9, 10, 15, 17, 18, 21, 23, 24, 25, 31, 34, 35, 38, 40 |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Probability Mass Functions                                                   |                                   |                                  |                                                                           |                                    |
|         |                                                   | 2.  Named Discrete Distributions                                                 |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 4       | September 30th, 2024                              | From Discrete to Continuous Random Variables:                                    | DFO §6.2, 6.5                     | BH §5.1-5.8                      | BH §5.10: 1, 3, 4, 6, 8, 9, 18, 19, 21, 24, 25, 27, 34, 37, 42, 44        |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Calculus Review                                                              | GS §5.2, 4.2, 6.3                 |                                  |                                                                           |                                    |
|         |                                                   | 2.  Probability Density Functions                                                |                                   |                                  |                                                                           |                                    |
|         |                                                   | 3.  Cumulative Distribution Functions                                            |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 5       | October 7th, 2024                                 | Heavy Tails: What and Why?                                                       | None (test prep)                  | BH §6.1-6.3                      | Handout to be distributed                                                 | **Test I: Covering Weeks 1-4**     |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   |                                                                                  |                                   |                                  | BH §6.10: 3, 9, 11, 12                                                    |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 6       | **TUESDAY October 15th, 2024** (Note date change) | Random Vectors:                                                                  | DFO §5.1-5.2                      | BH §7.1-7.2,§ A.3, §A.6-A.7      | BH §7.8: 1, 4, 5, 6, 8, 9, 10, 11, 13, 14, 16, 17, 18,                    |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Review of Multivariable Calculus                                             |                                   |                                  |                                                                           |                                    |
|         |                                                   | 2.  Joint Distributions                                                          |                                   |                                  |                                                                           |                                    |
|         |                                                   | 3.  Marginal Distributions                                                       |                                   |                                  |                                                                           |                                    |
|         |                                                   | 4.  Conditional Distributions                                                    |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 7       | October 21st, 2024                                | Covariance and Correlation: Working with Linear Combinations of Random Variables | GS §7.1-7.2                       | BH §6.4-6.6, §7.3                | BH §7.8: 31, 33, 36, 37, 38, 41, 43, 48, 49, 51, 54, 59                   |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 8       | October 28th, 2024                                | The Multivariate Normal Distribution and its Progeny:                            | DFO §2.1-2.7, §3.1-3.4, \$4.2-4.4 | BH §7.5-7.6, §10.4               | BH 7.8: §72, 73, 74, 77, 78,                                              |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Review of Linear Algebra                                                     |                                   |                                  | Handout to be provided                                                    |                                    |
|         |                                                   | 2.  Properties of the Multivariate Normal Distribution                           |                                   |                                  |                                                                           |                                    |
|         |                                                   | 3.  Derived Distributions                                                        |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 9       | November 4th, 2024                                | **Special Topics**: Probability, Polling, and Prediction                         |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 10      | November 11th, 2024                               | Perils and Paradoxes in Expectations:                                            | None (test prep)                  | DFO §8.1-8.3, §8.6               | BH §4.12: 17                                                              | **Test II: Covering Weeks 5-8**    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   | 1.  Selection and Sampling Biases                                                |                                   | BH §9.1-9.3, §9.5-9.7            | §9.9: 1, 13, 15, 16, 25, 29, 38, 39, 40, 43,                              |                                    |
|         |                                                   | 2.  Implications for (Over-)Fitting of Models                                    |                                   |                                  |                                                                           |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 11      | November 18th, 2024                               | Probability Inequalities and Limit Theorems                                      | GS §8.1-8.2                       | BH §10.1-10.2                    | BH §10.7:                                                                 |                                    |
|         |                                                   |                                                                                  |                                   |                                  |                                                                           |                                    |
|         |                                                   |                                                                                  |                                   |                                  | 1, 2, 4, 6, 7, 13, 15, 16, 21,                                            |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 12      | November 25th, 2024                               | Distributional Limits and the Central Limit Theorem                              | GS §9.1-9.3                       | BH §10.3                         | BH §10.7: 22, 23, 24, 26, 28, 29, 30, 36, 37                              |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 13      | December 2nd, 2024                                | Concentration of Measure: Generalized Limit Theory                               | Handout to be distributed.        | Handout to be distributed.       | Handout to be distributed.                                                |                                    |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+
| 14      | December 9th, 2024                                | Computing with Randomness: an Introduction to Monte Carlo Methods                | None (test prep)                  |                                  | None (last day of class)                                                  | **Test III: Covering Weeks 10-13** |
+---------+---------------------------------------------------+----------------------------------------------------------------------------------+-----------------------------------+----------------------------------+---------------------------------------------------------------------------+------------------------------------+

: {.hover}

**Note on Week 9:** On November 4th (Election Eve), we will meet at our regular time (6:05pm). Instead of our usual format (quiz, peer evaluation, review, new material), we will discuss a set of election-related special topics, including i) construction and evaluation of probabilistic election forecasts; ii) martingale properties and their implications for forecasting; iii) conformal calibration as applied to real-time election results. New Material from Week 8 (Multivariate Normal Distribution) will be quizzed during Week 10 (November 11th).

**`All syllabus provisions subject to change with suitable advance notice.`**

Changes will be announced in class and via Brightspace.

## Pre- and Post-Reading Suggestions

Students learn material most effectively when exposed to it on multiple occasions, ideally using alternative presentations strategies and formats.[^2] To this end, suggested *pre-reading* and *post-reading* is provided for each week of the course. Students are encouraged to *pre-read* the recommended text, which typically presents that week's material in a less technical / more intuitive manner, before each week's course session. Similarly, students are encouraged to review the *post-reading* for each week after lecture to see additional examples of topics covered.

[^2]: Haoyu Chen and Jiongjiong Yang. "Multiple Exposures Enhance Both Item Memory and Contextual Memory over Time". *Frontiers in Psychology* **11**. November 2020. [DOI:10.3389/fpsyg.2020.565169](https://doi.org/10.3389/fpsyg.2020.565169)

While lectures will focus primarily on 'big picture' and 'major themes', the recommended reading, especially the post-reading from BH, provides additional coverage of relevant technical detail.

Students with prior exposure to topics in probability may choose to omit pre-reading. In general, GS pre-reading introduces fundamentals of probability while DFO pre-reading reviews relevant mathematical tools. Students may also elect to consume post-reading as part of completing that week's practice problems, rather than as a separate activity.

Students are responsible for all material appearing in the pre-reading, in lecture, and in the post-reading, but students will not be evaluated on reading *per se*.
